# Generated by Django 5.1.4 on 2025-06-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="typ",
            field=models.CharField(default="comedy", max_length=200),
        ),
    ]
