# Generated by Django 5.1.4 on 2025-06-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_moviedata_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="image",
            field=models.ImageField(
                default="Images/None/Noimg.jpg", upload_to="Images/"
            ),
        ),
    ]
